name: Python application

on:
  push:
    branches: [ develop, feature/docs ]
  pull_request:
    branches: [ develop, feature/docs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-intl myst_parser sphinx-autoapi
    - name: Generate .po files for translation
      run: |
        sphinx-build -b gettext docs/source docs/_build/gettext
        cd docs
        sphinx-intl update -p _build/gettext -l ru
        cd ..
    - name: Commit report
      run: |
        git config --global user.name 'translation_generator'
        git config --global user.email 'vladimir.litvinenko.1997@gmail.com'
        if [ -n "$(git status --porcelain)" ]; then
          git add docs/locales;
          git commit -m "Automated translation generation" --allow-empty;
          git push origin ${GITHUB_REF#refs/heads/};
        else
          echo "no changes";
        fi
        
